const {REST,Routes,SlashCommandBuilder,PermissionFlagsBits,ChannelType}=require("discord.js");

const admin=PermissionFlagsBits.Administrator.bitfield;
const mod=PermissionFlagsBits.ManageGuild.bitfield;
const commands=[
 new SlashCommandBuilder().setName("city").setDescription("Open your City dashboard."),
 new SlashCommandBuilder().setName("profile").setDescription("View your City profile."),
 new SlashCommandBuilder().setName("job").setDescription("Choose and play a main job."),
 new SlashCommandBuilder().setName("sidejob").setDescription("Play a short side job."),
 new SlashCommandBuilder().setName("crime").setDescription("Take a fictional in-game criminal job."),
 new SlashCommandBuilder().setName("jail").setDescription("View your jail status."),
 new SlashCommandBuilder().setName("bank").setDescription("Open your bank."),
 new SlashCommandBuilder().setName("market").setDescription("Open the City market."),
 new SlashCommandBuilder().setName("house").setDescription("View your property."),
 new SlashCommandBuilder().setName("vehicle").setDescription("View your vehicle."),
 new SlashCommandBuilder().setName("business").setDescription("Manage your business."),
 new SlashCommandBuilder().setName("quest").setDescription("View today's quest."),
 new SlashCommandBuilder().setName("ticket").setDescription("Post or manage the support panel."),
 new SlashCommandBuilder().setName("map").setDescription("Explore City districts."),
 new SlashCommandBuilder().setName("pet").setDescription("Adopt and care for a City pet."),
 new SlashCommandBuilder().setName("events").setDescription("See current City events."),
 new SlashCommandBuilder().setName("achievements").setDescription("View your achievements."),
 new SlashCommandBuilder().setName("trade").setDescription("Manage player trades."),
 new SlashCommandBuilder().setName("police").setDescription("Open the fictional Police career panel."),
 new SlashCommandBuilder().setName("leaderboard").setDescription("View the City leaderboard."),
 new SlashCommandBuilder().setName("admin").setDescription("Open the administrator panel.").setDefaultMemberPermissions(admin),

 new SlashCommandBuilder().setName("warn").setDescription("Warn a member.").setDefaultMemberPermissions(mod).addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason")),
 new SlashCommandBuilder().setName("kick").setDescription("Kick a member.").setDefaultMemberPermissions(mod).addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason")),
 new SlashCommandBuilder().setName("ban").setDescription("Ban a member.").setDefaultMemberPermissions(mod).addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason")),
 new SlashCommandBuilder().setName("timeout").setDescription("Timeout a member.").setDefaultMemberPermissions(mod).addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addIntegerOption(o=>o.setName("minutes").setDescription("Duration").setMinValue(1).setMaxValue(40320).setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason")),
 new SlashCommandBuilder().setName("clear").setDescription("Delete recent messages.").setDefaultMemberPermissions(mod).addIntegerOption(o=>o.setName("amount").setDescription("1-100").setMinValue(1).setMaxValue(100).setRequired(true)),
 new SlashCommandBuilder().setName("serverinfo").setDescription("View server information."),
 new SlashCommandBuilder().setName("userinfo").setDescription("View member information.").addUserOption(o=>o.setName("user").setDescription("Member")),
 new SlashCommandBuilder().setName("setup").setDescription("Open the server setup panel.").setDefaultMemberPermissions(admin),
 new SlashCommandBuilder().setName("config").setDescription("View or change bot configuration.").setDefaultMemberPermissions(admin).addStringOption(o=>o.setName("key").setDescription("Setting").setRequired(false)).addStringOption(o=>o.setName("value").setDescription("Value").setRequired(false)),
 new SlashCommandBuilder().setName("automod").setDescription("Configure automatic moderation.").setDefaultMemberPermissions(mod).addBooleanOption(o=>o.setName("enabled").setDescription("Enable AutoMod").setRequired(true)),
 new SlashCommandBuilder().setName("welcome").setDescription("Set the welcome channel.").setDefaultMemberPermissions(admin).addChannelOption(o=>o.setName("channel").setDescription("Welcome channel").addChannelTypes(ChannelType.GuildText).setRequired(true)),
 new SlashCommandBuilder().setName("autorole").setDescription("Set the automatic member role.").setDefaultMemberPermissions(admin).addRoleOption(o=>o.setName("role").setDescription("Role").setRequired(true)),
 new SlashCommandBuilder().setName("logs").setDescription("Set moderation logs channel.").setDefaultMemberPermissions(admin).addChannelOption(o=>o.setName("channel").setDescription("Logs channel").addChannelTypes(ChannelType.GuildText).setRequired(true)),
 new SlashCommandBuilder().setName("verify").setDescription("Post a verification panel.").setDefaultMemberPermissions(admin),
 new SlashCommandBuilder().setName("giveaway").setDescription("Start a giveaway.").setDefaultMemberPermissions(mod).addStringOption(o=>o.setName("prize").setDescription("Prize").setRequired(true)).addIntegerOption(o=>o.setName("minutes").setDescription("Duration in minutes").setMinValue(1).setMaxValue(10080).setRequired(true)).addIntegerOption(o=>o.setName("winners").setDescription("Number of winners").setMinValue(1).setMaxValue(20)),
 new SlashCommandBuilder().setName("poll").setDescription("Create a poll.").setDefaultMemberPermissions(mod).addStringOption(o=>o.setName("question").setDescription("Question").setRequired(true)).addStringOption(o=>o.setName("options").setDescription("Options separated by |").setRequired(true)),
 new SlashCommandBuilder().setName("suggest").setDescription("Send a suggestion.").addStringOption(o=>o.setName("text").setDescription("Suggestion").setRequired(true)),
 new SlashCommandBuilder().setName("level").setDescription("View your level."),
 new SlashCommandBuilder().setName("rank").setDescription("View your server rank."),
 new SlashCommandBuilder().setName("remind").setDescription("Set a reminder.").addIntegerOption(o=>o.setName("minutes").setDescription("Minutes").setMinValue(1).setMaxValue(10080).setRequired(true)).addStringOption(o=>o.setName("text").setDescription("Reminder").setRequired(true)),
 new SlashCommandBuilder().setName("afk").setDescription("Set an AFK status.").addStringOption(o=>o.setName("reason").setDescription("Reason")),
 new SlashCommandBuilder().setName("role").setDescription("Add or remove a role from a member.").setDefaultMemberPermissions(mod).addStringOption(o=>o.setName("action").setDescription("add/remove").setRequired(true).addChoices({name:"Add",value:"add"},{name:"Remove",value:"remove"})).addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addRoleOption(o=>o.setName("role").setDescription("Role").setRequired(true)),
 new SlashCommandBuilder().setName("serverstats").setDescription("View server bot statistics."),
 new SlashCommandBuilder().setName("8ball").setDescription("Ask the magic 8-ball.").addStringOption(o=>o.setName("question").setDescription("Question").setRequired(true)),

 new SlashCommandBuilder().setName("coinflip").setDescription("Flip a coin."),
 new SlashCommandBuilder().setName("dice").setDescription("Roll dice.").addIntegerOption(o=>o.setName("sides").setDescription("Number of sides").setMinValue(2).setMaxValue(100).setRequired(false)),
 new SlashCommandBuilder().setName("trivia").setDescription("Get a trivia question."),
 new SlashCommandBuilder().setName("guess").setDescription("Guess a number from 1 to 10.").addIntegerOption(o=>o.setName("number").setDescription("Your guess").setMinValue(1).setMaxValue(10).setRequired(true)),
 new SlashCommandBuilder().setName("wyr").setDescription("Get a Would You Rather question."),
 new SlashCommandBuilder().setName("fortune").setDescription("Get a random fortune."),
 new SlashCommandBuilder().setName("rep").setDescription("Give reputation to a member.").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)),
 new SlashCommandBuilder().setName("daily").setDescription("Claim your daily reward."),
 new SlashCommandBuilder().setName("weekly").setDescription("Claim your weekly reward."),
 new SlashCommandBuilder().setName("shop").setDescription("Open the community shop."),
 new SlashCommandBuilder().setName("inventory").setDescription("View your inventory."),
 new SlashCommandBuilder().setName("event").setDescription("View community events."),
 new SlashCommandBuilder().setName("birthday").setDescription("Set your birthday.").addStringOption(o=>o.setName("date").setDescription("MM-DD").setRequired(true)),
 new SlashCommandBuilder().setName("counting").setDescription("Show the counting channel configuration.").setDefaultMemberPermissions(mod),
 new SlashCommandBuilder().setName("starboard").setDescription("Configure the starboard channel.").setDefaultMemberPermissions(mod).addChannelOption(o=>o.setName("channel").setDescription("Starboard channel").addChannelTypes(ChannelType.GuildText).setRequired(true)),
 new SlashCommandBuilder().setName("slowmode").setDescription("Set channel slowmode.").setDefaultMemberPermissions(mod).addIntegerOption(o=>o.setName("seconds").setDescription("0-21600").setMinValue(0).setMaxValue(21600).setRequired(true)),
 new SlashCommandBuilder().setName("lock").setDescription("Lock the current channel.").setDefaultMemberPermissions(mod),
 new SlashCommandBuilder().setName("unlock").setDescription("Unlock the current channel.").setDefaultMemberPermissions(mod),
 new SlashCommandBuilder().setName("note").setDescription("Store a private server note.").addStringOption(o=>o.setName("text").setDescription("Note").setRequired(true)),
 new SlashCommandBuilder().setName("notes").setDescription("View your server notes."),
 new SlashCommandBuilder().setName("eventcreate").setDescription("Create a server event.").setDefaultMemberPermissions(mod).addStringOption(o=>o.setName("name").setDescription("Event name").setRequired(true)).addStringOption(o=>o.setName("when").setDescription("Event time").setRequired(true)),
 new SlashCommandBuilder().setName("customcommand").setDescription("Create a custom command.").setDefaultMemberPermissions(admin).addStringOption(o=>o.setName("name").setDescription("Command name").setRequired(true)).addStringOption(o=>o.setName("response").setDescription("Response").setRequired(true)),
 new SlashCommandBuilder().setName("commands").setDescription("Browse available bot modules."),
 new SlashCommandBuilder().setName("botinfo").setDescription("View bot information."),
 new SlashCommandBuilder().setName("roleinfo").setDescription("View role information.").addRoleOption(o=>o.setName("role").setDescription("Role").setRequired(true)),
 new SlashCommandBuilder().setName("channelinfo").setDescription("View channel information.").addChannelOption(o=>o.setName("channel").setDescription("Channel").setRequired(false)),
 new SlashCommandBuilder().setName("diagnostics").setDescription("Run a bot diagnostics check.").setDefaultMemberPermissions(admin), new SlashCommandBuilder().setName("rps").setDescription("Play rock paper scissors.").addStringOption(o=>o.setName("choice").setDescription("Your choice").setRequired(true).addChoices({name:"Rock",value:"rock"},{name:"Paper",value:"paper"},{name:"Scissors",value:"scissors"}))

 new SlashCommandBuilder().setName("selfrole").setDescription("Manage a self role.").addStringOption(o=>o.setName("action").setDescription("add/remove").setRequired(true).addChoices({name:"Add",value:"add"},{name:"Remove",value:"remove"})).addRoleOption(o=>o.setName("role").setDescription("Role").setRequired(true)),
 new SlashCommandBuilder().setName("voicetemp").setDescription("Create a temporary voice channel."),
 new SlashCommandBuilder().setName("antiraid").setDescription("Configure anti-raid protection.").setDefaultMemberPermissions(admin).addBooleanOption(o=>o.setName("enabled").setDescription("Enable").setRequired(true)),
 new SlashCommandBuilder().setName("sticky").setDescription("Set a sticky message.").setDefaultMemberPermissions(mod).addStringOption(o=>o.setName("text").setDescription("Message").setRequired(true)),
 new SlashCommandBuilder().setName("season").setDescription("View the current server season."),
 new SlashCommandBuilder().setName("collection").setDescription("View your collectible badges."),
 new SlashCommandBuilder().setName("backup").setDescription("Export server bot settings.").setDefaultMemberPermissions(admin)
];
async function registerCommands(){
 const rest=new REST({version:"10"}).setToken(process.env.DISCORD_TOKEN);
 const route=process.env.GUILD_ID?Routes.applicationGuildCommands(process.env.CLIENT_ID,process.env.GUILD_ID):Routes.applicationCommands(process.env.CLIENT_ID);
 await rest.put(route,{body:commands.map(x=>x.toJSON())});
 console.log("⚙️ Registered",commands.length,"commands.");
}
module.exports={registerCommands};