const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,PermissionFlagsBits}=require("discord.js");
const {ensurePlayer,getPlayer,updatePlayer,topPlayers,q}=require("../database");
const {jobs}=require("../city/jobs"); const {sideJobs}=require("../city/sidejobs");
const {dashboard,mainRow,jobSelect,startActivity,finishActivity,profile,money,rnd}=require("./game");

const itemCatalog={
 pizza:{name:"🍕 Pizza",price:80},cola:{name:"🥤 Cola",price:30},medkit:{name:"🧰 Repair Kit",price:250},
 crystal:{name:"💎 Crystal",price:1200},card:{name:"🃏 Mystery Card",price:400},fuel:{name:"⛽ Fuel Can",price:120}
};
function shopEmbed(){return new EmbedBuilder().setTitle("🏪 CITY MARKET").setDescription("Choose an item to buy.").addFields(Object.entries(itemCatalog).map(([k,v])=>({name:v.name,value:money(v.price),inline:true})));}
function inventoryEmbed(p){const inv=p.inventory||{};const lines=Object.entries(inv).filter(([,n])=>n>0).map(([k,n])=>`${itemCatalog[k]?.name||k} × **${n}**`);return new EmbedBuilder().setTitle("🎒 INVENTORY").setDescription(lines.length?lines.join("\n"):"Your inventory is empty.");}
function jailSeconds(p){return p.jailed_until?Math.max(0,Math.ceil((new Date(p.jailed_until)-Date.now())/1000)):0;}
async function handleCommand(i){
 const p=await getPlayer(i.user.id,i.guildId);
 if(i.commandName==="city")return i.reply({embeds:[dashboard(p)],components:[mainRow()]});
 if(i.commandName==="profile")return i.reply({embeds:[profile(p,i.user)]});
 if(i.commandName==="job")return i.reply({content:"💼 Choose your main career:",components:[jobSelect("jobs","job")],ephemeral:true});
 if(i.commandName==="sidejob")return i.reply({content:"📦 Choose a side job:",components:[jobSelect("side","side")],ephemeral:true});
 if(i.commandName==="crime")return i.reply({embeds:[new EmbedBuilder().setTitle("🚨 CRIMINAL DISTRICT").setDescription("Fictional in-game activities. Higher reward means higher arrest risk.")],components:[new ActionRowBuilder().addComponents(
  new ButtonBuilder().setCustomId("crime:shop").setLabel("Store Robbery").setEmoji("🏪").setStyle(ButtonStyle.Danger),
  new ButtonBuilder().setCustomId("crime:car").setLabel("Car Theft").setEmoji("🚗").setStyle(ButtonStyle.Danger),
  new ButtonBuilder().setCustomId("crime:heist").setLabel("Bank Heist").setEmoji("🏦").setStyle(ButtonStyle.Danger)
 )]});
 if(i.commandName==="jail"){const s=jailSeconds(p);return i.reply({embeds:[new EmbedBuilder().setTitle(s?"⛓️ JAIL":"🔓 NO JAIL").setDescription(s?`Time remaining: **${s}s**`:"You're free.")],components:s?[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("jail:exercise").setLabel("Exercise").setEmoji("🏋️").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("jail:cards").setLabel("Cards").setEmoji("🃏").setStyle(ButtonStyle.Secondary))]:[]})}
 if(i.commandName==="bank")return i.reply({embeds:[new EmbedBuilder().setTitle("🏦 CITY BANK").addFields({name:"Wallet",value:money(p.money),inline:true},{name:"Bank",value:money(p.bank),inline:true})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("bank:deposit").setLabel("Deposit $100").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("bank:withdraw").setLabel("Withdraw $100").setStyle(ButtonStyle.Secondary))]});
 if(i.commandName==="market")return i.reply({embeds:[shopEmbed()]});
 if(i.commandName==="inventory")return i.reply({embeds:[inventoryEmbed(p)]});
 if(i.commandName==="house")return i.reply({embeds:[new EmbedBuilder().setTitle("🏠 YOUR HOME").setDescription(`${p.house.type} — Level ${p.house.level}\nRating: ⭐ ${p.house.rating}/100`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("house:upgrade").setLabel("Upgrade $5,000").setEmoji("🔨").setStyle(ButtonStyle.Primary))]});
 if(i.commandName==="vehicle")return i.reply({embeds:[new EmbedBuilder().setTitle("🚗 GARAGE").setDescription(`${p.vehicle.type}\nFuel: ${p.vehicle.fuel}%\nCondition: ${p.vehicle.condition}%`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("vehicle:buy").setLabel("Buy Starter Car $8,000").setEmoji("🚗").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("vehicle:fuel").setLabel("Fuel $120").setEmoji("⛽").setStyle(ButtonStyle.Secondary))]});
 if(i.commandName==="business")return i.reply({embeds:[new EmbedBuilder().setTitle("🏪 YOUR BUSINESS").setDescription(p.business.name?`${p.business.name}\nType: ${p.business.type}\nLevel: ${p.business.level}\nBalance: ${money(p.business.balance)}`:"You don't own a business yet.")],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("business:open").setLabel("Open Cafe $25,000").setEmoji("🏪").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("business:upgrade").setLabel("Upgrade $10,000").setEmoji("⬆️").setStyle(ButtonStyle.Secondary))]});
 if(i.commandName==="quest")return i.reply({embeds:[new EmbedBuilder().setTitle("🗺️ DAILY QUEST").setDescription("Complete 2 activities today.\n\nReward: **$750 + 40 XP**\n\nProgress is counted automatically from Jobs and Side Jobs.")],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("quest:claim").setLabel("Claim if complete").setStyle(ButtonStyle.Success))]});
 if(i.commandName==="leaderboard"){const rows=await topPlayers(i.guildId);return i.reply({embeds:[new EmbedBuilder().setTitle("🏆 CITY LEADERBOARD").setDescription(rows.map((x,n)=>`${n+1}. <@${x.user_id}> — **${money(x.money)}**`).join("\n")||"No citizens yet.") ]});}
 if(i.commandName==="admin"){if(!i.memberPermissions.has(PermissionFlagsBits.Administrator))return i.reply({content:"❌ Administrator permission required.",ephemeral:true});return i.reply({embeds:[new EmbedBuilder().setTitle("🛠️ GUARDIA ADMIN PANEL").setDescription("Administrator-only control center.")],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("admin:stats").setLabel("Stats").setEmoji("📊").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("admin:economy").setLabel("Economy").setEmoji("💰").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("admin:reset").setLabel("Reset Player").setEmoji("♻️").setStyle(ButtonStyle.Danger))],ephemeral:true});}
}
async function handleButton(i){
 if(i.isButton()&&/^(ticket|pet|police|trade):/.test(i.customId)) return;
 const [scope,action,key,answer,expected]=i.customId.split(":"); const p=await getPlayer(i.user.id,i.guildId);
 if(scope==="dash"){if(action==="profile")return i.reply({embeds:[profile(p,i.user)]});if(action==="jobs")return i.reply({content:"💼 Choose your main career:",components:[jobSelect("jobs","job")],ephemeral:true});if(action==="sidejobs")return i.reply({content:"📦 Choose a side job:",components:[jobSelect("side","side")],ephemeral:true});if(action==="market")return i.reply({embeds:[shopEmbed()]});if(action==="crime")return i.reply({content:"Use /crime to enter the Criminal District.",ephemeral:true});}
 if(scope==="play")return finishActivity(i,action==="job"?"job":"side",key,decodeURIComponent(answer),decodeURIComponent(expected));
 if(scope==="crime"){
  if(p.jailed_until&&new Date(p.jailed_until)>new Date())return i.reply({content:"⛓️ You're already in jail.",ephemeral:true});
  const data={shop:{reward:[300,650],wanted:1,sentence:90},car:{reward:[500,1100],wanted:2,sentence:180},heist:{reward:[1200,3000],wanted:3,sentence:360}}[action];if(!data)return;
  const success=Math.random()>.35; const stats={...(p.stats||{}),crimes:Number(p.stats?.crimes||0)+1};
  if(!success){stats.arrests=Number(stats.arrests||0)+1;await updatePlayer(i.user.id,i.guildId,{wanted:Math.min(5,p.wanted+data.wanted),jailed_until:new Date(Date.now()+data.sentence*1000),stats});return i.update({content:`🚔 **CAUGHT!**\nSentence: **${data.sentence}s**`,embeds:[],components:[]});}
  const r=rnd(...data.reward);await updatePlayer(i.user.id,i.guildId,{money:Number(p.money)+r,wanted:Math.min(5,p.wanted+data.wanted),stats});return i.update({content:`🚨 Crime succeeded. You got **${money(r)}**. Wanted: **${Math.min(5,p.wanted+data.wanted)}**`,embeds:[],components:[]});
 }
 if(scope==="bank"){if(action==="deposit"){if(Number(p.money)<100)return i.reply({content:"Not enough cash.",ephemeral:true});await updatePlayer(i.user.id,i.guildId,{money:Number(p.money)-100,bank:Number(p.bank)+100});return i.update({content:"🏦 Deposited $100.",embeds:[],components:[]});}if(action==="withdraw"){if(Number(p.bank)<100)return i.reply({content:"Not enough in your bank.",ephemeral:true});await updatePlayer(i.user.id,i.guildId,{money:Number(p.money)+100,bank:Number(p.bank)-100});return i.update({content:"🏦 Withdrew $100.",embeds:[],components:[]});}}
 if(scope==="house"&&action==="upgrade"){if(Number(p.money)<5000)return i.reply({content:"You need $5,000.",ephemeral:true});const h={...p.house,level:Number(p.house.level)+1,rating:Math.min(100,Number(p.house.rating)+8),type:Number(p.house.level)>=4?"Mansion":p.house.type};await updatePlayer(i.user.id,i.guildId,{money:Number(p.money)-5000,house:h});return i.update({content:"🏠 Home upgraded!",embeds:[],components:[]});}
 if(scope==="vehicle"){if(action==="buy"){if(p.vehicle.type!=="None")return i.reply({content:"You already own a vehicle.",ephemeral:true});if(Number(p.money)<8000)return i.reply({content:"You need $8,000.",ephemeral:true});await updatePlayer(i.user.id,i.guildId,{money:Number(p.money)-8000,vehicle:{type:"City Compact",fuel:100,condition:100}});return i.update({content:"🚗 Vehicle purchased!",embeds:[],components:[]});}if(action==="fuel"){if(p.vehicle.type==="None")return i.reply({content:"Buy a vehicle first.",ephemeral:true});if(Number(p.money)<120)return i.reply({content:"You need $120.",ephemeral:true});await updatePlayer(i.user.id,i.guildId,{money:Number(p.money)-120,vehicle:{...p.vehicle,fuel:100}});return i.update({content:"⛽ Tank filled.",embeds:[],components:[]});}}
 if(scope==="business"){if(action==="open"){if(p.business.name)return i.reply({content:"You already own a business.",ephemeral:true});if(Number(p.money)<25000)return i.reply({content:"You need $25,000.",ephemeral:true});await updatePlayer(i.user.id,i.guildId,{money:Number(p.money)-25000,business:{name:"City Cafe",type:"Cafe",level:1,balance:0,rating:50}});return i.update({content:"🏪 Your City Cafe is open!",embeds:[],components:[]});}if(action==="upgrade"){if(!p.business.name)return i.reply({content:"Open a business first.",ephemeral:true});if(Number(p.money)<10000)return i.reply({content:"You need $10,000.",ephemeral:true});await updatePlayer(i.user.id,i.guildId,{money:Number(p.money)-10000,business:{...p.business,level:Number(p.business.level)+1,rating:Math.min(100,Number(p.business.rating)+5)}});return i.update({content:"⬆️ Business upgraded!",embeds:[],components:[]});}}
 if(scope==="quest"){const total=Number(p.stats?.jobs||0)+Number(p.stats?.sidejobs||0);if(total<2)return i.reply({content:"🗺️ Not completed yet. Play two activities first.",ephemeral:true});return i.reply({content:"🎉 Quest reward: **$750 + 40 XP**!",ephemeral:true});}
 if(scope==="jail")return i.reply({content:jailSeconds(p)?"⛓️ Prison activity completed.":"🔓 You're free.",ephemeral:true});
 if(scope==="admin"){if(!i.memberPermissions.has(PermissionFlagsBits.Administrator))return i.reply({content:"❌ Administrator permission required.",ephemeral:true});if(action==="stats"){const {rows}=await q("SELECT COUNT(*)::int AS members,COALESCE(SUM(money),0)::bigint AS cash FROM players WHERE guild_id=$1",[i.guildId]);return i.reply({content:`📊 Citizens: **${rows[0].members}**\n💰 Total cash: **${money(rows[0].cash)}**`,ephemeral:true});}if(action==="economy")return i.reply({content:"💰 Economy controls are modular and ready for expansion.",ephemeral:true});return i.reply({content:"♻️ Select a target before using destructive admin actions.",ephemeral:true});}
}
async function registerInteractions(client){
 client.on("interactionCreate",async i=>{try{if(!i.guildId)return;if(i.isChatInputCommand()){await ensurePlayer(i.user.id,i.guildId);return handleCommand(i);}if(i.isStringSelectMenu()){if(i.customId==="pick:job"){const k=i.values[0];await updatePlayer(i.user.id,i.guildId,{job:k});return startActivity(i,k,"job");}if(i.customId==="pick:side")return startActivity(i,i.values[0],"side");}if(i.isButton())return handleButton(i);}catch(e){console.error(e);const m={content:"⚠️ Something went wrong. Check Railway logs.",ephemeral:true};if(i.replied||i.deferred)await i.followUp(m).catch(()=>{});else await i.reply(m).catch(()=>{});}});
}
module.exports={registerInteractions};
