const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,PermissionFlagsBits}=require("discord.js");
const {getPlayer,updatePlayer,getSettings,setSettings,q}=require("./database");
const answers=["It is certain.","Most likely.","Ask again later.","Probably not.","Very doubtful."];
const games=["rock","paper","scissors"];
const admins=i=>i.memberPermissions?.has(PermissionFlagsBits.Administrator);
const mods=i=>admins(i)||i.memberPermissions?.has(PermissionFlagsBits.ManageGuild);
const ch=(g,id)=>id?g.channels.cache.get(id):null;
async function log(g,title,text){const s=await getSettings(g.id);const c=ch(g,s.logChannel);if(c)await c.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(text).setTimestamp()]}).catch(()=>{});}
async function handleFeatureCommand(i){
 const n=i.commandName;
 if(["setup","config","automod","welcome","autorole","logs","verify","giveaway","poll"].includes(n)&&!mods(i))return i.reply({content:"❌ Server management permission required.",ephemeral:true});
 if(n==="setup"){const s=await getSettings(i.guildId);return i.reply({embeds:[new EmbedBuilder().setTitle("⚙️ SERVER SETUP").setDescription("Per-server configuration center.").addFields({name:"👋 Welcome",value:s.welcomeChannel?"On":"Off",inline:true},{name:"🛡️ AutoMod",value:s.automod?"On":"Off",inline:true},{name:"📋 Logs",value:s.logChannel?"On":"Off",inline:true},{name:"💡 Suggestions",value:s.suggestionChannel?"Custom":"Current channel",inline:true})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("setup:stats").setLabel("Settings").setEmoji("⚙️").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("setup:verify").setLabel("Verification").setEmoji("✅").setStyle(ButtonStyle.Success))],ephemeral:true});}
 if(n==="config"){const key=i.options.getString("key"),value=i.options.getString("value");const allowed=["welcomeChannel","autoRole","logChannel","suggestionChannel","verifiedRole","starboardChannel","ticketCategory","staffRole","ticketLog","automod"];if(!key)return i.reply({content:"Settings: "+allowed.join(", "),ephemeral:true});if(!allowed.includes(key))return i.reply({content:"❌ Unknown setting.",ephemeral:true});if(value===null)return i.reply({content:key+" = "+String((await getSettings(i.guildId))[key]||"not set"),ephemeral:true});await setSettings(i.guildId,{[key]:value});return i.reply({content:"✅ Saved.",ephemeral:true});}
 if(n==="automod"){const v=i.options.getBoolean("enabled");await setSettings(i.guildId,{automod:v});return i.reply({content:"🛡️ AutoMod "+(v?"enabled":"disabled")+".",ephemeral:true});}
 if(n==="welcome"){await setSettings(i.guildId,{welcomeChannel:i.options.getChannel("channel").id});return i.reply({content:"👋 Welcome channel saved.",ephemeral:true});}
 if(n==="autorole"){await setSettings(i.guildId,{autoRole:i.options.getRole("role").id});return i.reply({content:"🎭 Auto role saved.",ephemeral:true});}
 if(n==="logs"){await setSettings(i.guildId,{logChannel:i.options.getChannel("channel").id});return i.reply({content:"📋 Logs channel saved.",ephemeral:true});}
 if(n==="verify"){const s=await getSettings(i.guildId);if(!s.verifiedRole)return i.reply({content:"❌ Set verifiedRole with /config.",ephemeral:true});await i.channel.send({embeds:[new EmbedBuilder().setTitle("✅ Verification").setDescription("Click below to verify.")],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("verify:accept").setLabel("Verify").setEmoji("✅").setStyle(ButtonStyle.Success))]});return i.reply({content:"✅ Panel posted.",ephemeral:true});}
 if(n==="poll"){const opts=i.options.getString("options").split("|").map(x=>x.trim()).filter(Boolean).slice(0,10),emo=["1️⃣","2️⃣","3️⃣","4️⃣","5️⃣","6️⃣","7️⃣","8️⃣","9️⃣","🔟"];if(opts.length<2)return i.reply({content:"❌ Use at least two options separated by |.",ephemeral:true});const m=await i.channel.send({embeds:[new EmbedBuilder().setTitle("📊 "+i.options.getString("question")).setDescription(opts.map((x,k)=>emo[k]+" "+x).join("\\n"))]});for(let k=0;k<opts.length;k++)await m.react(emo[k]).catch(()=>{});return i.reply({content:"📊 Poll created.",ephemeral:true});}
 if(n==="giveaway"){const prize=i.options.getString("prize"),minutes=i.options.getInteger("minutes"),winners=i.options.getInteger("winners")||1,ends=new Date(Date.now()+minutes*60000);const m=await i.channel.send({embeds:[new EmbedBuilder().setTitle("🎉 GIVEAWAY").setDescription("Prize: **"+prize+"**\\nWinners: **"+winners+"**\\nEnds: <t:"+Math.floor(ends.getTime()/1000)+":R>\\nReact with 🎉 to enter!") ]});await m.react("🎉");await q("INSERT INTO giveaways(guild_id,channel_id,message_id,prize,winners,ends_at) VALUES($1,$2,$3,$4,$5,$6)",[i.guildId,i.channelId,m.id,prize,winners,ends]);return i.reply({content:"🎉 Giveaway started.",ephemeral:true});}
 if(n==="suggest"){const s=await getSettings(i.guildId),c=ch(i.guild,s.suggestionChannel)||i.channel;await c.send({embeds:[new EmbedBuilder().setTitle("💡 Suggestion").setDescription(i.options.getString("text")).addFields({name:"Author",value:"<@"+i.user.id+">",inline:true},{name:"Status",value:"🟡 Pending",inline:true})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("suggest:approve").setLabel("Approve").setEmoji("✅").setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId("suggest:deny").setLabel("Deny").setEmoji("❌").setStyle(ButtonStyle.Danger))]});return i.reply({content:"💡 Suggestion submitted.",ephemeral:true});}
 if(n==="level"||n==="rank"){const p=await getPlayer(i.user.id,i.guildId),xp=Number(p.stats?.chatXp||0),lvl=Math.floor(xp/100)+1;if(n==="level")return i.reply({content:"⭐ Level "+lvl+" • XP "+(xp%100)+"/100"});const z=await q("SELECT user_id,COALESCE((stats->>'chatXp')::int,0) xp FROM players WHERE guild_id=$1 ORDER BY xp DESC",[i.guildId]);const r=z.rows.findIndex(x=>x.user_id===i.user.id)+1;return i.reply({content:r?"🏆 Rank #"+r:"Start chatting to rank up."});}
 if(n==="remind"){const due=new Date(Date.now()+i.options.getInteger("minutes")*60000);await q("INSERT INTO reminders(guild_id,user_id,channel_id,text,due_at) VALUES($1,$2,$3,$4,$5)",[i.guildId,i.user.id,i.channelId,i.options.getString("text"),due]);return i.reply({content:"⏰ Reminder set for <t:"+Math.floor(due.getTime()/1000)+":R>.",ephemeral:true});}
 if(n==="afk"){const s=await getSettings(i.guildId);await setSettings(i.guildId,{afk:{...(s.afk||{}),[i.user.id]:i.options.getString("reason")||"AFK"}});return i.reply({content:"💤 AFK enabled.",ephemeral:true});}
 if(n==="role"){const m=i.options.getMember("user"),r=i.options.getRole("role"),a=i.options.getString("action");if(r.position>=i.guild.members.me.roles.highest.position)return i.reply({content:"❌ Role hierarchy prevents this.",ephemeral:true});if(a==="add")await m.roles.add(r);else await m.roles.remove(r);return i.reply({content:"✅ Role updated.",ephemeral:true});}
 if(n==="serverstats"){const z=await q("SELECT COUNT(*)::int members,COALESCE(SUM(money),0)::bigint cash FROM players WHERE guild_id=$1",[i.guildId]);return i.reply({content:"📊 Citizens: "+z.rows[0].members+" • Economy: $"+Number(z.rows[0].cash).toLocaleString()});}
 if(n==="8ball")return i.reply({content:"🎱 "+answers[Math.floor(Math.random()*answers.length)]});
 if(n==="rps"){const u=i.options.getString("choice"),b=games[Math.floor(Math.random()*3)],win=u===b?"🤝 Tie!":((u==="rock"&&b==="scissors")||(u==="paper"&&b==="rock")||(u==="scissors"&&b==="paper"))?"🎉 You win!":"🤖 Bot wins!";return i.reply({content:"🪨📄✂️ You: **"+u+"** • Bot: **"+b+"**\\n"+win});}
 return false;
}
async function handleFeatureButton(i){if(!i.isButton())return false;if(i.customId==="setup:stats"){const s=await getSettings(i.guildId);return i.reply({content:Object.entries(s).filter(x=>x[0]!=="afk").map(x=>x[0]+" = "+x[1]).join("\\n")||"No settings.",ephemeral:true});}if(i.customId==="setup:verify"){const s=await getSettings(i.guildId);if(!s.verifiedRole)return i.reply({content:"❌ Set verifiedRole first.",ephemeral:true});await i.channel.send({embeds:[new EmbedBuilder().setTitle("✅ Verification").setDescription("Click below to verify.")],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("verify:accept").setLabel("Verify").setEmoji("✅").setStyle(ButtonStyle.Success))]});return i.reply({content:"✅ Posted.",ephemeral:true});}if(i.customId==="verify:accept"){const s=await getSettings(i.guildId),r=i.guild.roles.cache.get(s.verifiedRole);if(!r)return i.reply({content:"❌ Verification role missing.",ephemeral:true});await i.member.roles.add(r).catch(()=>{});return i.reply({content:"✅ Verified!",ephemeral:true});}if(i.customId.startsWith("giveaway:join:")){const id=i.customId.split(":")[2],z=await q("SELECT * FROM giveaways WHERE id=$1 AND guild_id=$2 AND ended=FALSE",[id,i.guildId]);if(!z.rows[0])return i.reply({content:"❌ Giveaway ended.",ephemeral:true});const a=Array.isArray(z.rows[0].participants)?z.rows[0].participants:[];if(a.includes(i.user.id))return i.reply({content:"🎉 You are already entered.",ephemeral:true});a.push(i.user.id);await q("UPDATE giveaways SET participants=$1 WHERE id=$2",[a,id]);return i.reply({content:"🎉 Entry confirmed!",ephemeral:true});}if(i.customId.startsWith("suggest:")){if(!mods(i))return i.reply({content:"❌ Staff permission required.",ephemeral:true});const status=i.customId.endsWith("approve")?"🟢 Approved":"🔴 Denied",e=EmbedBuilder.from(i.message.embeds[0]);e.setFields((i.message.embeds[0].fields||[]).map(f=>f.name==="Status"?{name:"Status",value:status,inline:true}:f));await i.message.edit({embeds:[e],components:[]});return i.reply({content:"✅ Updated.",ephemeral:true});}return false;}
async function handleMessage(m){if(!m.guild||m.author.bot)return;const s=await getSettings(m.guild.id);if(s.afk?.[m.author.id]){const a={...s.afk};delete a[m.author.id];await setSettings(m.guild.id,{afk:a});}const u=m.mentions.users.find(x=>s.afk?.[x.id]);if(u)await m.reply("💤 <@"+u.id+"> is AFK: "+s.afk[u.id]).catch(()=>{});if(s.automod&&/(https?:\\/\\/|discord\\.gg\\/|@everyone|@here)/i.test(m.content)&&!m.member.permissions.has(PermissionFlagsBits.ManageMessages)){await m.delete().catch(()=>{});await log(m.guild,"🛡️ AutoMod","Removed a message from <@"+m.author.id+">");return;}const p=await getPlayer(m.author.id,m.guild.id),st={...(p.stats||{})},now=Date.now();if(now-Number(st.chatLast||0)>60000){st.chatLast=now;st.chatXp=Number(st.chatXp||0)+10;await updatePlayer(m.author.id,m.guild.id,{stats:st});}}
async function handleMemberJoin(m){const s=await getSettings(m.guild.id);if(s.autoRole){const r=m.guild.roles.cache.get(s.autoRole);if(r)await m.roles.add(r).catch(()=>{});}if(s.welcomeChannel){const c=ch(m.guild,s.welcomeChannel);if(c)await c.send({embeds:[new EmbedBuilder().setTitle("👋 Welcome!").setDescription("Welcome <@"+m.id+"> to **"+m.guild.name+"**!").setTimestamp()]}).catch(()=>{});}}
async function processTimers(client){const z=await q("SELECT * FROM reminders WHERE done=FALSE AND due_at<=NOW() LIMIT 50");for(const r of z.rows){const c=client.channels.cache.get(r.channel_id);if(c)await c.send("⏰ <@"+r.user_id+"> reminder: **"+r.text+"**").catch(()=>{});await q("UPDATE reminders SET done=TRUE WHERE id=$1",[r.id]);}const g=await q("SELECT * FROM giveaways WHERE ended=FALSE AND ends_at<=NOW() LIMIT 25");for(const x of g.rows){const c=client.channels.cache.get(x.channel_id),a=Array.isArray(x.participants)?[...x.participants]:[],w=[];while(a.length&&w.length<Number(x.winners)){w.push(a.splice(Math.floor(Math.random()*a.length),1)[0]);}if(c)await c.send({embeds:[new EmbedBuilder().setTitle("🎉 GIVEAWAY ENDED").setDescription("Prize: **"+x.prize+"**\n"+(w.length?w.map(id=>"<@"+id+">").join(", "):"No entries."))]}).catch(()=>{});await q("UPDATE giveaways SET ended=TRUE WHERE id=$1",[x.id]);}}
module.exports={handleFeatureCommand,handleFeatureButton,handleMessage,handleMemberJoin,processTimers};